### ISSUE TITLE
Why is this library only compatible with 101?

### ISSUE THREAD

**Issue by q2dg** [dantler/LircRemote101#1]
I mean...if it is an speed issue, ARM-based boards like Due/Zero/MKR1000 should be compatible too, shouldn't?

**Comment by dantler** [comment]
This library is bit-banging a 38KHz clock signal! To elaborate, it's using
delay functions to synthesize the 38KHz square waves needed to produce IR
signals. I wrote up an explanation of how IR remotes work here.
https://dantler.us/how-infrared-remotes-work/

Delay functions may behave differently on different platforms. I also
suspect that one function I'm using (`delayTicks`) might not even exist on
other platforms!

Beyond that, it's only tested and tuned on the Arduino101! You could likely
get this library to work without much trouble if you have an oscilloscope.

**Comment by q2dg** [comment]
Ok, thanks for the explanation.
If you don't mind, I'll close this issue, then.
